FROM node:22-alpine

WORKDIR /var/www/front

# Copia apenas o package.json e package-lock.json (se existir)
COPY ./banco_php_malvader/src/frontend/package.json ./banco_php_malvader/src/frontend/package.h
COPY ./banco_php_malvader/src/frontend/package-lock.json ./package-lock.json

# Instala as dependências
RUN npm install

# Copia todo o conteúdo do frontend para dentro do contêiner
COPY ./src/frontend/. .

# Comando para iniciar o projeto
CMD ["npm", "run", "dev"]